### ISSUE TITLE
Upgraded to ArcPro 3.4 and whitebox tools broke.

### ISSUE THREAD

**Issue by Hornbydd** [opengeos/WhiteboxTools-ArcGIS#55]
Hi,

I recently upgraded my version of Arcpro to 3.4 and whitebox toolbox suddenly had a red exclamation mark next to it. A hint highlighted a line starting with `sys`. So I opened up the toolbox to see why it would be complaining about this.

I noticed that whitebox does not import `sys` module so I put an import in. VSCode stopped complaining and after restarting ArcPro it all seems to be working OK now.

Top of code is now:

```
import arcpy
import os, sys
import webbrowser
from WBT.whitebox_tools import WhiteboxTools
if sys.version_info < (3, 0):
    from StringIO import StringIO
else:
    from io import StringIO
```

Although it might be implicit I think for future releases you need to explicitly import `sys`

**Comment by giswqs** [comment]
Thank you for reporting. It has been fixed in #56
